#                 .__               .__               
# _______  ______ |  |  __ __  ____ |__| ____   ______
# \_  __ \ \____ \|  | |  |  \/ ___\|  |/    \ /  ___/
#  |  | \/ |  |_> >  |_|  |  / /_/  >  |   |  \\___ \ 
#  |__|    |   __/|____/____/\___  /|__|___|  /____  >
#          |__|             /_____/         \/     \/ 
#

permission:
  default: "rspawn"
  setspawn: "rspawn.setspawn"
  spawn: "rspawn.spawn"
  spawn-region: "rspawn.spawn.region"
  spawn-region-player: "rspawn.spawn.region.player"
  reload: "rspawn.reload"
  help: "rspawn.help"
  tp-bypass: "rspawn.bypass" # Отмена кулдауна, постоянной телепортации после перезахода и т.д

settings:
  tp-fall-y: -10
  # Телепортировать если ты упал ниже высоты указанной в "tp-fall-y" Телепортирует на глобальный спавн
  tp-fall: true
  # Телепортировать ли игрока если он застрял в блоке (тп либо на локальный спавн либо на глобальный или же начинается проверка на блоки сверху)
  tp-onBlock: true
  tp-maxBlock: 10 # Сколько будет проверяться блоков вверх для телепортации(чем ниже тем меньше нагружает)

messages:
  set-g-spawn: "&aГлобальный спавн был установлен"
  set-l-spawn: "&aЛокальный спавн был установлен"
  region-no: "&cУказанный регион не был найден на сервере"
  command-usage-player: "&cЭту команду можно использовать только игроку"
  command-usage: "&cИспользование /rspawn help"
  no-permission: "&cУ вас нет прав использовать эту команду"
  reload: "&aПлагин [rSpawn] был перезагружен"
  no-g-spawn: "&aГлобальный спавн не установлен"
  teleport-cancel: "&cТелепортация была отменена"
  teleport-accept: "&aВы успешно были телепортированы"
  help:
    - " "
    - "&f/rspawn help - это сообщение"
    - "&f/rspawn reload - перезагрузить конфигурацию"
    - "&f/rspawn setspawn <global/local> <регион<если_нужен>>"
    - "&f/spawn <регион> <игрок> - телепортация на спавн"
    - " "